/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/*
 * TURN ON LED 1 - Connected to PB5
 * READ GPIO  -  PA1
 */

#include <stdint.h>

int main(void){


	// RCC base address + Offset of GPIO clock enable register (RCC_IOPENR)
	// 0x40021000 + 0x2c
	uint32_t *pClkCtlReg = (uint32_t*) 0x4002102c;

	// PORT B
	// GPIOB base address  + offset of GPIO port mode register (GPIOx_MODER) => (0x50000400 + 0x00)
	uint32_t *pPortBModeReg = (uint32_t*) 0x50000400;
	// GPIOB base address  + offset of GPIO port output data register (GPIOx_ODR) => (0x50000400 + 0x14)
	uint32_t *pPortBOutReg = (uint32_t*) 0x50000414;

	// PORT A
	// GPIOA base address  + offset of GPIO port mode register (GPIOx_MODER) => (0X50000000 + 0x00)
	uint32_t *pPortAModeReg = (uint32_t*) 0X50000000;
	// GPIOA base address  + offset of GPIO port input data register (GPIOx_IDR) => (0X50000000 + 0x10)
	uint32_t *pPortAInReg = (uint32_t*) 0X50000010;

	// Enable the clock for GPIO B Peripheral
	*pClkCtlReg |= (1 << 1);
	// Enable the clock for GPIO A Peripheral
	*pClkCtlReg |= (1 << 0);

	// Configure the mode of the PB5 pin as output
	// clear 11th and 10th bit positions (CLEAR)
	*pPortBModeReg &= ~(3 << 10);
	// make 10th bit position as 1 (SET)
	*pPortBModeReg |= (1 << 10);

	// Configure the mode of the PA0 pin as input
	// clear 1th and 0th bit positions (CLEAR)
	//  Input mode - 00
	*pPortAModeReg &= ~(3 << 0);
	// make 0th&1st bit position as 1 (SET)
	//*pPortAModeReg |= (3 << 0);


	while(1){
		uint8_t ldr_reading = *pPortAInReg & 0x1;

		if(ldr_reading > 0)
			// Turn ON LED
			*pPortBOutReg |= (1 << 5);

		else
			// Turn OFF LED
			*pPortBOutReg &= ~(1 << 5);

	}
}

