/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/*
 * TURN ON LED 1
 * Connected in PB5
 */
#include <stdint.h>

int main(void){

	// RCC base address + Offset of GPIO clock enable register (RCC_IOPENR)
	// 0x40021000 + 0x2c
	uint32_t *pClkCtlReg = (uint32_t*) 0x4002102c;
	// GPIOB base address  + offset of GPIO port mode register (GPIOx_MODER)
	// 0x50000400 + 0x00
	uint32_t *pPortBModeReg = (uint32_t*) 0x50000400;
	// GPIOB base address  + GPIO port output data register (GPIOx_ODR)
	// 0x50000400 + 0x14
	uint32_t *pPortBOutReg = (uint32_t*) 0x50000414;

	// Enable the clock for GPIO B Peripheral
	// 0x00000002
	*pClkCtlReg = *pClkCtlReg | 0x2;

	// Configure the mode of the IO pin as output
	// clear 11th and 10th bit positions (CLEAR)
	// 0xFFFFF3FF
	*pPortBModeReg = *pPortBModeReg & 0xFFFFF3FF;
	// make 10th bit position as 1 (SET)
	*pPortBModeReg = *pPortBModeReg | 0x00000400;

	// Set 5th bit of the output data register to make I/O pin-5 HIGH
	*pPortBOutReg = *pPortBOutReg | 0x0020;

	while(1){

	}
}
