// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"todo-api/todo-api/models"
)

// PostTodosCreatedCode is the HTTP code returned for type PostTodosCreated
const PostTodosCreatedCode int = 201

/*
PostTodosCreated ToDo created

swagger:response postTodosCreated
*/
type PostTodosCreated struct {

	/*
	  In: Body
	*/
	Payload *models.ToDo `json:"body,omitempty"`
}

// NewPostTodosCreated creates PostTodosCreated with default headers values
func NewPostTodosCreated() *PostTodosCreated {

	return &PostTodosCreated{}
}

// WithPayload adds the payload to the post todos created response
func (o *PostTodosCreated) WithPayload(payload *models.ToDo) *PostTodosCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post todos created response
func (o *PostTodosCreated) SetPayload(payload *models.ToDo) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostTodosCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
