/*
* UPDATE - NEW/OLD
* INSERT - NEW
* DELETE - OLD
*/

CREATE OR REPLACE TRIGGER user_after_update
AFTER UPDATE ON mytable FOR EACH ROW
DECLARE
    
BEGIN
    DBMS_OUTPUT.PUT_LINE(:OLD.name);
    DBMS_OUTPUT.PUT_LINE(:NEW.name);
END;


UPDATE mytable SET name = 'hai' WHERE name = 'hi';