swagger: "2.0"
info:
  description: "This is a sample ToDo API."
  version: "1.0.0"
  title: "ToDo API"
  
paths:
  /todos:
    get:
      summary: "Get all ToDos"
      responses:
        200:
          description: "A list of ToDos."
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ToDo"
    post:
      summary: "Create a new ToDo"
      parameters:
        - in: "body"
          name: "body"
          description: "The ToDo to create"
          required: true
          schema:
            $ref: "#/definitions/ToDo"
      responses:
        201:
          description: "ToDo created"
          schema:
            $ref: "#/definitions/ToDo"

definitions:
  ToDo:
    type: "object"
    required:
      - id
      - task
    properties:
      id:
        type: "integer"
        format: "int64"
      task:
        type: "string"
      completed:
        type: "boolean"
