-- package
CREATE OR REPLACE PACKAGE USER_PACKAGE
AS
PROCEDURE ADD_USER(
  user_id   IN NUMBER,
  user_name IN VARCHAR2
);
PROCEDURE GET_USER(
  user_id   IN NUMBER
); 
PROCEDURE GET_COUNT;

END USER_PACKAGE;